version: '2'
services:
  security:
    build: .
    ports:
      - '3007:3007'
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
    volumes:
      - ./sample-service/api:/app/api
  db:
    build: ./database-service
